syntax = "proto3";

package voting;

service VotingService {
	rpc GetCandidates (Empty) returns (CandidatesList);
	rpc Vote (VoteRequest) returns (VoteResponse);
	rpc GetResults (Empty) returns (ResultsList);
}

message Empty {}

message Candidate {
	int32 id = 1;
	string name = 2;
	int32 votes = 3;
}

message CandidatesList {
	repeated Candidate candidates = 1;
}

message VoteRequest {
	int32 candidateId = 1;
}

message VoteResponse {
	string message = 1;
}

message ResultsList {
	repeated Candidate candidates = 1;
}
